/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HorarioRouteImport } from './routes/horario'
import { Route as ProfesoresRouteImport } from './routes/profesores'
import { Route as ResumenRouteImport } from './routes/resumen'
import { Route as RevisionesRouteImport } from './routes/revisiones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorarioRoute = HorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesoresRoute = ProfesoresRouteImport.update({
  id: '/profesores',
  path: '/profesores',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumenRoute = ResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionesRoute = RevisionesRouteImport.update({
  id: '/revisiones',
  path: '/revisiones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/horario': typeof HorarioRoute
  '/profesores': typeof ProfesoresRoute
  '/resumen': typeof ResumenRoute
  '/revisiones': typeof RevisionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/horario': typeof HorarioRoute
  '/profesores': typeof ProfesoresRoute
  '/resumen': typeof ResumenRoute
  '/revisiones': typeof RevisionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/horario': typeof HorarioRoute
  '/profesores': typeof ProfesoresRoute
  '/resumen': typeof ResumenRoute
  '/revisiones': typeof RevisionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/horario' | '/profesores' | '/resumen' | '/revisiones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/horario' | '/profesores' | '/resumen' | '/revisiones'
  id: '__root__' | '/' | '/horario' | '/profesores' | '/resumen' | '/revisiones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HorarioRoute: typeof HorarioRoute
  ProfesoresRoute: typeof ProfesoresRoute
  ResumenRoute: typeof ResumenRoute
  RevisionesRoute: typeof RevisionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horario': {
      id: '/horario'
      path: '/horario'
      fullPath: '/horario'
      preLoaderRoute: typeof HorarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesores': {
      id: '/profesores'
      path: '/profesores'
      fullPath: '/profesores'
      preLoaderRoute: typeof ProfesoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumen': {
      id: '/resumen'
      path: '/resumen'
      fullPath: '/resumen'
      preLoaderRoute: typeof ResumenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisiones': {
      id: '/revisiones'
      path: '/revisiones'
      fullPath: '/revisiones'
      preLoaderRoute: typeof RevisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HorarioRoute: HorarioRoute,
  ProfesoresRoute: ProfesoresRoute,
  ResumenRoute: ResumenRoute,
  RevisionesRoute: RevisionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
